stages:
  - test
  - report

#cache:
#  key: composer-cache
#  paths:
#    - .composer-cache/

.test:
  before_script:
    # display PHP version
    - php -v
    # install system packages
    - apt-get update && apt-get install -y --force-yes git unzip
    # install extensions
#    - docker-php-ext-install gmp
    # install composer
    - php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer.sig');"
    - php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    - php -r '$expected = file_get_contents("/tmp/composer.sig"); $actual = hash_file("sha384", "/tmp/composer-setup.php"); exit(intval(!hash_equals($expected, $actual)));'
    - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - chmod +x /usr/local/bin/composer
    - rm /tmp/composer-setup.php /tmp/composer.sig
    # cache dependencies
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer update
    - tests/tests.sh

# lowest version
test-5.3:
  extends: .test
  stage: test
  image: php:5.3

test-5.4:
  extends: .test
  stage: test
  image: php:5.4

test-5.5:
  extends: .test
  stage: test
  image: php:5.5

test-5.6:
  extends: .test
  stage: test
  image: php:5.6

test-7.0:
  extends: .test
  stage: test
  image: php:7.0

test-7.1:
  extends: .test
  stage: test
  image: php:7.1

test-7.2:
  extends: .test
  stage: test
  image: php:7.2

test-7.3:
  extends: .test
  stage: test
  image: php:7.3

test-7.4:
  extends: .test
  stage: test
  image: php:7.4

test-8.0:
  extends: .test
  stage: test
  image: php:8.0

test-8.1:
  extends: .test
  stage: test
  image: php:8.1-rc

test-rc:
  extends: .test
  stage: test
  image: php:rc
